### ISSUE TITLE
calc refinements

### ISSUE THREAD

**Issue by mrdwab** [tomaztk/Useless_R_functions#9]
Hi. I'm assuming that the goal of this exercise is about constructing a function programmatically, not the output. If it were just the output, I'm sure that you'd just want something like:

    calc2 <- function(a, b, oper) sprintf('Result is %g', match.fun(oper)(a, b))

But looking at your approach below:

https://github.com/tomaztk/Useless_R_functions/blob/8467c211b9113f1b626f01d55a280d591891c06d/functions/GenerateCalculator.R#L38-L51

I think it would be easier to ditch the loops and use `sprintf` for a lot of the function creation instead. Something like:

```r
df <- expand.grid(numA = 1:10, oper = c("+", "-", "/", "*"), numB = 1:10, stringsAsFactors = FALSE)
rr <- sapply(1:nrow(df), function(x) match.fun(df[x, "oper"])(df[x, "numA"], df[x, "numB"]))
template <- ' if (a == %s & b == %s & oper == "%s") print("Result is %g")\n '
f <- sprintf("calc <- function(a, b, oper) {\n%s\n}", 
             paste0(with(df, sprintf(template, numA, numB, oper, rr)), collapse = ""))
eval(parse(text = f))
```

Changes were:

* `expand.grid` to create the "df"
* `sapply` to pre-calculate the results
* `sprintf` to piece together the function

**Comment by tomaztk** [comment]
Hi,

Thanks for the issue.
Wanted to use loop instead of apply (sapply) function myself, but decide to go with loop as part of  "uselessness". But overall, nice improvement with expand.grid and sprintf.

Merging to main branch.
Best, Tomaž

**Comment by tomaztk** [comment]
Added to solution.
Thanks
